### ISSUE TITLE
C++ support

### ISSUE THREAD

**Issue by Pombal** [fungos/cr#3]
If the DLL is written in C++ without exception handling or RTTI, would it work? If not, what would need to implemented? Also, any plans on adding C++ support in the future? Thanks!

**Comment by fungos** [comment]
C++ is tricky, but it works if you consider some things:
- For heap allocated objects that lives between reloads, if the vtable changes things will break;
- Any static object destructor or even non trivial constructor may cause unexpected behavior in your code as during reload. When doing the unload, the destructor for static objects will run and you should know your objects to see if that will be a problem or not, the same during the load as static objects will be constructed.

Simple put, it works but you need to know C++ very well to see the traps everywhere.
Otherwise, I'd recommend [RCC++](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus) for complex c++ projects.

**Comment by Pombal** [comment]
Thank you for the quick reply, I understand the limitations :)
